# Generated by Django 5.2.1 on 2025-05-09 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='study1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_name', models.CharField(max_length=100)),
                ('study_phase', models.CharField(max_length=100)),
                ('sponser_name', models.CharField(max_length=100)),
                ('study_description', models.TextField()),
            ],
        ),
    ]
