# Generated by Django 5.2.1 on 2025-05-10 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='study1',
            old_name='sponser_name',
            new_name='sponsor_name',
        ),
    ]
